CREATE TABLE IF NOT EXISTS User (
user_id    VARCHAR(255) PRIMARY KEY,
user_name  VARCHAR(255) UNIQUE,
email      VARCHAR(255) NOT NULL,
deleted    BOOLEAN      DEFAULT FALSE NOT NULL,
create_ts  TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP(6),
update_ts  TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)
);

CREATE TABLE IF NOT EXISTS UserBalance (
user_id       VARCHAR(255)  NOT NULL PRIMARY KEY,
balance       DECIMAL(10,2) NOT NULL,
deleted       BOOLEAN       DEFAULT FALSE NOT NULL,
create_ts     TIMESTAMP(6)  DEFAULT CURRENT_TIMESTAMP(6),
update_ts     TIMESTAMP(6)  DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)
);

CREATE TABLE IF NOT EXISTS UserAsset (
user_id       VARCHAR(255)  NOT NULL,
asset_code    VARCHAR(50)   NOT NULL,
quantity      INT           NOT NULL,
deleted       BOOLEAN       DEFAULT FALSE,
create_ts     TIMESTAMP(6)  DEFAULT CURRENT_TIMESTAMP(6),
update_ts     TIMESTAMP(6)  DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
PRIMARY KEY (user_id, asset_code)
);

CREATE TABLE IF NOT EXISTS Asset (
asset_code    VARCHAR(50)  NOT NULL PRIMARY KEY,
asset_name    VARCHAR(255)  NOT NULL,
deleted       BOOLEAN      DEFAULT FALSE NOT NULL
create_ts     TIMESTAMP(6)  DEFAULT CURRENT_TIMESTAMP(6),
update_ts     TIMESTAMP(6)  DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)
);

CREATE TABLE IF NOT EXISTS AssetInfo (
id          INT            NOT NULL AUTO_INCREMENT PRIMARY KEY,
asset_code  VARCHAR(50)   NOT NULL,
value       DECIMAL(10,2)  NOT NULL,
ask         DECIMAL(10,2)  NOT NULL,
bid         DECIMAL(10,2)  NOT NULL,
weight      VARCHAR(10)    NOT NULL,
currency    VARCHAR(3)     NOT NULL,
deleted     BOOLEAN        DEFAULT FALSE NOT NULL,
create_ts   TIMESTAMP(6)   DEFAULT CURRENT_TIMESTAMP(6),
update_ts   TIMESTAMP(6)   DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)
FOREIGN KEY (asset_code) REFERENCES Asset(asset_code)
);



CREATE TABLE IF NOT EXISTS TransactionInfo (
transaction_id   VARCHAR(255)  NOT NULL PRIMARY KEY,
transaction_type VARCHAR(255)  NOT NULL,
ref_id           VARCHAR(255)  NOT NULL UNIQUE,
status           VARCHAR(255)  NOT NULL,
total_amount     DECIMAL(10,2) NOT NULL,
user_id          VARCHAR(255)  NOT NULL,
asset_code       VARCHAR(255)  NOT NULL,
quantity         INT           NOT NULL,
value            DECIMAL(10,2) NOT NULL,
currency         VARCHAR(255)  NOT NULL,
deleted          BOOLEAN       DEFAULT FALSE NOT NULL,
create_ts        TIMESTAMP(6)  DEFAULT CURRENT_TIMESTAMP(6),
update_ts        TIMESTAMP(6)  DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
FOREIGN KEY (asset_code) REFERENCES Asset(asset_code)
);
